### ISSUE TITLE
Problem with parsing dictionary.pyrad

### ISSUE THREAD

**Issue by kakash1hatake** [semaphor-dk/freeradius_exporter#1]
Hello
I've downloaded the project on my server and tryed to start the process and got an error:
```
    dict=Dictionary('/usr/local/share/freeradius_exporter/dictionary.freeradius.pyrad'))
  File "/usr/local/lib/python3.4/dist-packages/pyrad/dictionary.py", line 164, in __init__
    self.ReadDictionary(dict)
  File "/usr/local/lib/python3.4/dist-packages/pyrad/dictionary.py", line 386, in ReadDictionary
    self.__ParseAttribute(state, tokens)
  File "/usr/local/lib/python3.4/dist-packages/pyrad/dictionary.py", line 269, in __ParseAttribute
    state['tlvs'][parent_code].sub_attributes[code] = attribute
KeyError: 186
```

Comments say that there is a problem with parsing tlv, but they are already commented out.
I resolved the problem totally removing all 186.* attributes, but it is a bit weird, imho.

My os is debian 8 jessie and python version 3.4.2
Also I had to patch things about f-strings and hex conversion, but it is out of scope of this issue.

**Comment by jokjr** [comment]
Hm, that is indeed weird.
Which version of `pyrad` did `pip` pull in for you?

**Comment by jokjr** [comment]
@kakash1hatake I had a look, and I don't think there are any circumstances where the `186.*` attributes are exposed in the `status` interface, so we should probably just remove them from the custom dictionary we have.

It would be ideal if `pyrad` could parse the freeradius dictionary, but unfortunately various versions of the library have problems with that, which is why we ship our own trimmed-down version.

The hex conversion is unfortunately necessary for the authenticator generation, otherwise it will randomly fail when the random byte vector happens to start with `0x`.

The f-strings notation (`f'{a}'`) were introduced in a later revision of Python than you have and can probably be rewritten to work for you.

If you send me a diff or open a pull request with the changes that made it work on your platform I will incorporate a backwards compatible solution.

**Comment by kakash1hatake** [comment]
@jokjr got it

See #2

**Comment by kakash1hatake** [comment]
> Which version of `pyrad` did `pip` pull in for you?

pyrad is 2.4 and installed from pip.
pip is 19.1.1

Before installing the exporter I've upgraded all needed stuff
But also I have to mension that netaddr on python 3.4 should be 0.7 (I have 0.7.12) and if I install >= 0.8 the code gets broken(again due to f-strings that old python doesn't support)

**Comment by jokjr** [comment]
Noted, both Python 3.4 and Debian 8 (Jessie) are end-of-lifed, so this is slightly ancient, but I'm happy you made it work, and I hope you will like it - I think you are the first external user. :-)

**Comment by kakash1hatake** [comment]
Sure, I know about EOL, but currently servers live on that os. 
Moreover, we have some of them even on debian 7, but I haven't tested the exporter on them yet.
Maybe it's too ancient (it has python 3.2)

**Comment by jokjr** [comment]
No problem, let us know how it goes.
