### ISSUE TITLE
ImportError: cannot import name 'Enum'

### ISSUE THREAD

**Issue by primoz-p** [semaphor-dk/freeradius_exporter#4]
I followed your instructions in README but still getting this error. Do you have any idea why?
I always use **pip** so I have no experience with **setuptools**.

- Ubuntu 18.04.3
- Python3: 3.6.9
- python3-prometheus-client is already the newest version (0.1.1-1)
- python3-pyrad is already the newest version (2.0-3)

Oct 28 09:56:33 freeradius_exporter.py[1299465]: ImportError: cannot import name 'Enum'
Oct 28 09:56:33 systemd[1]: freeradius_exporter.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 09:56:33 systemd[1]: freeradius_exporter.service: Failed with result 'exit-code'.
Oct 28 09:56:43 systemd[1]: freeradius_exporter.service: Service hold-off time over, scheduling restart.
Oct 28 09:56:43 systemd[1]: freeradius_exporter.service: Scheduled restart job, restart counter is at 105.
Oct 28 09:56:43 systemd[1]: Stopped Prometheus exporter for data from FreeRADIUS.
Oct 28 09:56:43 systemd[1]: Started Prometheus exporter for data from FreeRADIUS.
Oct 28 09:56:44 freeradius_exporter.py[1299496]: Traceback (most recent call last):
Oct 28 09:56:44 freeradius_exporter.py[1299496]:   File "/usr/local/bin/freeradius_exporter.py", line 4, in <module>
Oct 28 09:56:44 freeradius_exporter.py[1299496]:     __import__('pkg_resources').run_script('freeradius-exporter==1.1', 'freeradius_exporter.py')
Oct 28 09:56:44 freeradius_exporter.py[1299496]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
Oct 28 09:56:44 freeradius_exporter.py[1299496]:     self.require(requires)[0].run_script(script_name, ns)
Oct 28 09:56:44 freeradius_exporter.py[1299496]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
Oct 28 09:56:44 freeradius_exporter.py[1299496]:     exec(script_code, namespace, namespace)
Oct 28 09:56:44 freeradius_exporter.py[1299496]:   File "/usr/local/lib/python3.6/dist-packages/freeradius_exporter-1.1-py3.6.egg/EGG-INFO/scripts/freeradius_exporter.py", line 4, in <module>
Oct 28 09:56:44 freeradius_exporter.py[1299496]:     __import__('pkg_resources').run_script('freeradius-exporter==1.1', 'freeradius_exporter.py')
Oct 28 09:56:44 freeradius_exporter.py[1299496]: ImportError: cannot import name 'Enum'
Oct 28 09:56:44 systemd[1]: freeradius_exporter.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 09:56:44 systemd[1]: freeradius_exporter.service: Failed with result 'exit-code'.

**Comment by jokjr** [comment]
@primoz-p 
It's failing to find the `Enum` class in `prometheus-client`.
It looks like your version is https://github.com/prometheus/client_python/releases/tag/v0.1.1 (from january 2018) while the latest release is `0.11.0`.
The `Enum` export was [present in November 2018](https://github.com/prometheus/client_python/blame/9a6e21de144e81ac666828aa843efb398d184b27/prometheus_client/__init__.py#L18), not sure if it was introduced then or before that.

Either way, could you try installing prometheus-client via `pip` to get a recent version instead of the old package in `ubuntu 18.04`?

If that's not possible for you I guess we can look at replacing the `Enum` usage with something more backwards compatible.

**Comment by jokjr** [comment]
@primoz-p Did installing from `pip` work out for you? I'll close this for now, let me know if there's additional trouble.
